### ISSUE TITLE
Data types

### ISSUE THREAD

**Issue by saifshaikh48** [nickghughes/CS4500-queue#4]
This Queue class only supports Objects.
Should users be able to store things like Strings in Queues as well?

Whenever I call peek or poll in the Queue class, it will return as an Object*, where the user will have to recast to a String* to use as a String*. 
Either 
1. There should be a way to explicitly handle Strings when inserting and getting them from the Array. One possible way to do this is to design a class specific Object that only handles Strings.
or
2. In your tests, please cast the results of your peek and poll calls to Strings.

**Comment by nickghughes** [comment]
I'm having a little trouble understanding what you're asking here. What purpose would casting to strings in the tests serve? The object methods are virtual so the inherited methods are the ones being called, so there should be no issue. The only time you would have to cast would be when actually manipulating or comparing said strings, which is not a part of this assignment or our tests.

**Comment by saifshaikh48** [comment]
You are right, it's more of a non-critical issue, but would make the lives of the API users easier in the future maybe.

**Comment by nickghughes** [comment]
Considering that casting has no real effect on runtime, and that the cast will always have to be performed (whether it is inside Queue or not), I don't see a reason to 1) cast when we don't need to and 2) add unnecessary duplicate code with an extra class. Assuming I'm reading your suggestions correctly
