### ISSUE TITLE
String constructor

### ISSUE THREAD

**Issue by saifshaikh48** [nickghughes/CS4500-queue#5]
Would you mind adding a string constructor that takes in char* instead of const char*? Also a default constructor String(){} would be helpful: should `String s = new String(); ` be valid construction? I think most would agree yes.

**Comment by saifshaikh48** [comment]
In addition please change the signatures of `concat(String *const s)` and `cmp(String *const s)` to concat(String *s)` and `cmp(String *s)`

**Comment by saifshaikh48** [comment]
https://piazza.com/class/k51bluky59n2jr?cid=345
Here is a good resource for standard Object and String class designs.

**Comment by nickghughes** [comment]
constructors are changed, and those method signatures I think should remain the same as per the "standard" object and string agreed upon on Piazza

**Comment by nickghughes** [comment]
In fact the exact Piazza post you linked is the reason I added const and deleted the constructors I just re-added for you. I think I'm leaving it as is now unless they make more changes to the standard classes. Closing this issue.
