### ISSUE TITLE
Object equals method (and String equals)

### ISSUE THREAD

**Issue by saifshaikh48** [nickghughes/CS4500-queue#6]
Is there a reason the equals method takes in const Objects*?
Having a `bool equals(Object* obj)` method would be immensely helpful and necessary.

**Comment by nickghughes** [comment]
I'm not sure I agree with it either, but it is the signature used in the "standard" class definitions we seem to have decided to adhere to on Piazza

**Comment by saifshaikh48** [comment]
Hmm the readme on the 'standard' repository ( https://github.com/chasebish/cwc_object_string ) is a good design imo. Is there a reason why const is used? I'm not sure what benefit this provides.

**Comment by nickghughes** [comment]
I think adding const makes the passed Object a copy instead of passing the actual pointer. This prevents us from unintentionally manipulating the passed Object

**Comment by saifshaikh48** [comment]
Hey could you update the inconsistent signatures:
Object class -- `virtual bool equals(Object const *other);`
String class -- `bool equals(Object const *other);`
Queue class -- `bool equals(Object* other);`

**Comment by nickghughes** [comment]
oh you're right, I think I'm gonna make Queue not an object, it's a bit unnecessary to have to deconstruct then reconstruct to test equality or to generate a hashcode

**Comment by saifshaikh48** [comment]
Not sure I understand, making all the equals method signatures the same (either `virtual bool equals(Object const *other);` or `virtual bool equals(Object *other);`) should be perfect. Almost positive Queue should inherit from Object, it has a hash and equal function anyway

**Comment by nickghughes** [comment]
I was just thinking in terms of it being tough to implement, but you're right. I've readded the methods, fixed the signatures, and added a new test

**Comment by saifshaikh48** [comment]
Thanks mate, will let you know if anything else arises but everything looks good on initial inspection
