### ISSUE TITLE
Queue Equals Test

### ISSUE THREAD

**Issue by terryr1** [nickghughes/CS4500-queue#8]
There's currently no test for the equals method in the queue class. I think it says somewhere in the assignment that everything needs to be tested. Thanks

**Comment by nickghughes** [comment]
This would have been tough to implement, and honestly borderline impossible. I'm following what some other groups have done and removed Object methods from Queue

**Comment by nickghughes** [comment]
Actually I've changed my mind on this and readded the methods, then added a test. Should be all good now 💯
